name: 🐞 Bug report
description: File a bug report.
title: '[Bug]: '
labels:
  - bug
assignees:
  - ngocjohn
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🛠️ Please provide the details below to help us address the issue.
  - type: input
    id: summary
    attributes:
      label: Short summary 📝
      description: A short summary of the bug
      placeholder: e.g., The application crashes when I click on 'Submit'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Detailed description 📋
      description: A detailed description of the bug
      placeholder: Describe the bug in detail, including steps to reproduce, expected behavior, and actual behavior.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version 📦
      description: The version of the application where the bug was found
      options:
        - v1.12.0
        - v1.11.0
        - v1.10.1
        - v1.10.0
        - v1.9.0
        - v1.8.1
        - v1.8.0
        - v1.7.2
        - v1.7.1
        - v1.7.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Card Configuration
      description: Your card YAML configuration
      render: yaml
      placeholder: |
        type: custom:lunar-phase-card
        entity: ""
        use_default: true
        use_custom: false
        use_entity: false
        show_background: true
        selected_language: en
        compact_view: false
        # Your configuration here
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment 🌐
      description: The environment in which the bug was found (e.g., browser, OS)
      placeholder: e.g., Chrome on Windows 10
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots 📂
      description: Any relevant logs or screenshots that can help identify the issue
      placeholder: Paste logs or upload screenshots
    validations:
      required: false
