name: Post release update

on: workflow_dispatch

permissions:
  contents: read

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
      - name: Run post release scripts
        run: npm run post-release

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet .github/ISSUE_TEMPLATE || echo "changed=true" >> $GITHUB_OUTPUT
          git diff --quiet README.md || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Debug output # check what changed git status output
        if: always()
        run: |
          git status
      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/ISSUE_TEMPLATE README.md
          git commit -m "chore: update bug report template and readme"
          ## for testing purpose only, no push to remote
          git log -1
          # git push
