name: Test action scripts
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: View releases of the repository
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./scripts/test-releases.js');
            console.log(script({github, context}));
