name: Update Bug Report Template

on: workflow_dispatch

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run update script
        uses: actions/github-script@v5
        id: release-check
        with:
          script: |
            const script = require('./scripts/update-bug-template.js');
            const hasChaned = script({github, context});
            return hasChaned;
          result-encoding: string
      - name: Debug output
        if: always()
        run: |
          echo "Releases changed: ${{ steps.release-check.outputs.result }}"
      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet .github/ISSUE_TEMPLATE || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/ISSUE_TEMPLATE
          git commit -m "chore: update issue template"
          git push
